apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/e28492-jp-ibm-com/open-liberty:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/e28492-jp-ibm-com/open-liberty:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: open-liberty
        chartPath: charts/open-liberty
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/e28492-jp-ibm-com/open-liberty"
          image.tag: "{{.TAG}}"
